export const FETCH_POST_SUCCESS='FETCH_POST_SUCCESS';

export const FETCH_POST_ERROR='FETCH_POST_ERROR';

export const FETCH_POST_REQUEST='FETCH_POST_REQUEST';

//PRODUCT
export const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS';

export const FETCH_PRODUCT_ERROR='FETCH_PRODUCT_ERROR';

export const FETCH_PRODUCT_REQUEST='FETCH_PRODUCT_REQUEST';
